version: '3'

tasks:
  build:
    cmds:
      - go build -o bin/mdprinter cmd/mdprinter/main.go
  install:
    cmds:
      - task: build
      - cp bin/mdprinter /usr/local/bin/mdprinter
      - chmod +x /usr/local/bin/mdprinter
      - task: clean
  clean:
    cmds:
      - rm -rf bin
  test:
    cmds:
      - go test -v .
  run-example:
    cmds:
      - task: build
      - bin/mdprinter examples/example.md -d examples/exampleData.json -s air
  
